name: trigger workflow

on: 
  pull_request:
  types: [opened, reopened]
    branches:
      - releases/*  #when pullrequest is opened then it will trigger to release branch
  # push:
  #   branches:
  #     - main  :- it can trigger mainly when we push to main branch
  # workflow_dispatch :- we can trigger manually from the Actions tab
  #[push] #triggers the workflow on every push to the repository


jobs:
  # manual workflow is the name of the job
  triggers:
    # Github managed runners are used to run the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo "Hello, krishna"
