name: trigger workflow

on: 
  push:
    branches:
      - feature/*
  # workflow_dispatch :- we can trigger manually from the Actions tab
  #[push] #triggers the workflow on every push to the repository


jobs:
  # manual workflow is the name of the job
  triggers:
    # Github managed runners are used to run the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo "Hello, krishna"
