name: GitHub context

on: [push] #triggers the workflow on every push to the repository


jobs:
  # say-hello is the name of the job
  github-context:
    # Github managed runners are used to run the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Run acontext info
        run: echo "${{ toJson(github) }}"
