name: gitHub secret context 

on: [push] #triggers the workflow on every push to the repository

env:
  Project: "roboshop"
  component: "shipping"
  environment: "dev"

jobs:

  github-context:
    # Github managed runners are used to run the job
    outputs:
      version: ${{ steps.tags.outputs.version }}
      image-name: ${{ steps.tags.outputs.image-name }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runner's shell
      - name: Run acontext info
        run: |
          echo "${{ toJson(github) }}"
          echo "branch name: ${{ github.ref_name }}"
      

      - name: access env variables
        run: |
          echo "Project name: $Project"
          echo "Component name: $component"
          echo "Environment: $environment"

      - name: access secrets   
        run: |
          echo "db_username: ${{ secrets.db_user }}" 
          echo "db_password: ${{ secrets.db_password }}"

      - name: access variables
        run: |
          echo "user_url: ${{ vars.user_url }}"

      #suppose we can to refer the output of previous step then we can access that on 
      - name: version and image-name
        id: tags
        run: |
          echo "version=1.0" >> $GITHUB_OUTPUT
          echo "image-name=shipping" >> $GITHUB_OUTPUT

      - name: refer the previous steps output  
        run: |
          echo "version: ${{ steps.tags.outputs.version }}"
          echo "image-name: ${{ steps.tags.outputs.image-name }}" 

      - name: version and image-name
        run: |
          echo "versions=1.0.0" >> $GITHUB_ENV
          echo "image=payment" >> $GITHUB_ENV

      - name: refer the variables of previous setup    
        run: |
          echo "version: $versions"
          echo "image: $image"

  deploy:
    runs-on: ubuntu-latest
    needs: github-context
    steps:
      - name: refer the previous job output  
        run: |
          echo "version: ${{ needs.github-context.outputs.version }}"
          echo "image-name: ${{ needs.github-context.outputs.image-name }}"        

  scans:
   runs-on: ubuntu-latest
   steps:
      - name: define scan
        run: echo "sonar scan"      