name: gitHub secret context 

on: [push] #triggers the workflow on every push to the repository

env:
  Project: "roboshop"
  component: "shipping"
  environment: "dev"

jobs:
  # say-hello is the name of the job
  github-context:
    # Github managed runners are used to run the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Run acontext info
        run: |
          echo "${{ toJson(github) }}"
          echo "branch name: ${{ github.ref_name }}"
      

      - name: access env variables
        run: |
          echo "Project name: $Project"
          echo "Component name: $component"
          echo "Environment: $environment"

      - name: access secrets   
        run: |
          echo "db_username: ${{ secrets.db_user }}" 
          echo "db_password: ${{ secrets.db_password }}"

      - name: access variables
        run: |
          echo "user_url: ${{ vars.user_url }}"