name: main branch workflow
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name}} #main branch workflow-main
  cancel-in-progress: true #if we push multiple times then it will cancel the previous workflow and run the latest one

jobs:
  main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: don't allow parallel execution in same branch
        run: sleep 60